Fix code coverage reporting
> [phpunit]
> Error:         Incorrect whitelist config, no code coverage will be generated.

Looks like somewhere along the way, the format for PHPUnit
changed, however, it's not an error that produces a non-zero
exit code, so I missed this.

The ocular.phar command also prints an error, and also without
non-zero exit code, hence making it hard to find when passing.

> [ocular.phar]
> Notifying that no code coverage data is available.